### ISSUE TITLE
Populate pre-onboarding template

### ISSUE THREAD

**Issue by rross0** [trueroll/onboarding#1]
I want to be able to coordinate onboarding activity for new DE hires using GitHub. I want to create an issue template for pre-onboarding work. This is the work that needs to be done *before* an employees first day. However, I don't know exactly what that work is. @jtwalsh0 can you help me work this out? If we need to just meet and talk it thought, let me know.

**Comment by jtwalsh0** [comment]
Here's one: 
```
### GitHub
- [ ] You will need a [GitHub](https://github.com/) account. If you do not already have one, [create a free GitHub account](https://github.com/signup) using your personal email address.
- [ ] Email us your user name 
- [ ] Create a GitHub token. The token will grant access to our secrets store (called "Vault"). It needs the `admin:org > read:org` scope. Store the token in a password manager. 
```

**Comment by jtwalsh0** [comment]
I have a list of things to do, but they probably don't go here. Can we discuss tomorrow?

**Comment by rross0** [comment]
Sure.

**Comment by jtwalsh0** [comment]
Partly addressed by https://github.com/trueroll/onboarding/pull/2
