### ISSUE TITLE
Welcome Christina Shaw

### ISSUE THREAD

**Issue by rross0** [trueroll/onboarding#6]
# Welcome

Welcome to TrueRoll, a small tech startup based in Chicago, Illinois. During your internship you will worth with our product team to explore new oportunities helping governemetns and private sector companies serve citizense better, faster, and smarter. 

This web page displays a GitHub issue. An issue defines a set of tasks or work that needs to be done. Issues are interactive - you can check checkboxes and make comments on the issues. Try it out:
- [ ] Got it.

## Your internship

Interns at TrueRoll are not 'cheap labor.' Interns are important members of our team, bringing new ideas and perspective to our work. We assign interns to work on meaningful projects that add value to the firma and advance our mission of improvig public administration and policy. You will get value out of your internship in proportion to the time and effort you put into it, so plan on spending about 20 hours per week working on your prject.

### Remote work

TrueRoll is a remote company, and you are not required to work in-person. Your work will be asynchronous. You will use your owner personal computer for work. We will use GitLab issues to coordinate our work.

- [ ] I have created a free GitLab account and commented below so Rob knows my username.

## Onboarding tasks

- [ ] I have receieved and completed my contractor paperwork.
- [ ] I have given my general availability to [Rob Ross](mailto:rob@trueroll.io)
- [ ] I have selected the project I want to work on from the list provided.

**Comment by cphelpsshaw** [comment]
cphelpsshaw
