### ISSUE TITLE
Will devs need access to Dropbox?

### ISSUE THREAD

**Issue by rross0** [trueroll/onboarding#9]
I am having trouble accessing data sent by Seattle because I don't have a Dropbox account associated with TR.  If such a dropbox account is necessary, please include it in the onboarding issue template.

**Comment by freepour** [comment]
@rross0 according to tyler, dropbox charges an insane amount to add additional users (500+/yr), I can coordinate with devs to either 
- put files that originate from dropbox into s3
- send links that will allow them the ability to download those files
